### ISSUE TITLE
Use a more practical phrase to rename this project

### ISSUE THREAD

**Issue by luojia65** [richardanaya/Executor#1]
This is a good project and might be the best first-of-all productional trial of async/await feature I have ever met. But as only one word 'executor' typically suggests one category of frameworks, the project name might be somehow too misleading, and maybe inconvenient for developers to exchange ideas. We may need to change the name. We can have a shorter word, we can have another practical word, we can abstract all features to conclude another name. If we rename this project, newsletter editors and blog writers are more convenient to express, to spread it wide; developers and maintainers would exchange ideas easier, and this project can be more welcomed by the community and maybe by some commercial projects. Thanks!

**Comment by richardanaya** [comment]
Appreciate you taking the time, but this is the name I want and it looks pretty in the projects that I use it in. At the end of the day that's what makes me happy.
