### ISSUE TITLE
Skull confusion

### ISSUE THREAD

**Issue by rfdonnelly** [richardanaya/Executor#3]
Hi, I'm confused by the use of the skull emoji.

![image](https://user-images.githubusercontent.com/28975/68905858-6cc8a900-06f7-11ea-9e78-e6eec07a15b2.png)

![image](https://user-images.githubusercontent.com/28975/68905870-74884d80-06f7-11ea-8117-b340f24ba5ab.png)

My initial thought was the project is dead and I shouldn't use it.  But I know that is not the case because this project was recently linked by the author on Reddit.  My second thought was that it is a play on the word "execute" as in "kill" or "executioner."

Regardless of the intent, the skull may turn potential users away 🤷‍♂.

**Comment by Tirka** [comment]
🥴

**Comment by richardanaya** [comment]
Great point! I'll remove it. Thanks for feedback.
