### ISSUE TITLE
Waking inside `poll` causes hang

### ISSUE THREAD

**Issue by paulkernfeld** [richardanaya/Executor#4]
Hi! I've been looking for an executor for some embedded programming, and I thought this might do the trick.

I was using [this suggestion](https://users.rust-lang.org/t/polling-in-new-era-futures/30531/2) for implementing futures that need to be polled continuously. I.e., waking the future from within `poll`. However, it looks like that causes `executor` to hang. Based on briefly looking at the code, I'm guessing this is because it's trying to re-lock the mutex while the mutex is already locked.

Below is the code I used to reproduce this error. I also include a test using `block_on` from the futures crate, which does seem to work.

```rust
use std::task::{Context, Poll};

struct ImmediatelyWakingFuture {
    first_call: bool
}

impl std::future::Future for ImmediatelyWakingFuture {
    type Output = ();

    fn poll(mut self: std::pin::Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        if self.first_call {
            self.first_call = false;
            cx.waker().wake_by_ref();
            Poll::Pending
        } else {
            Poll::Ready(())
        }
    }
}

#[test]
fn test_executor() {
    executor::block_on(ImmediatelyWakingFuture { first_call: true })
}

#[test]
fn test_futures() {
    futures::executor::block_on(ImmediatelyWakingFuture { first_call: true })
}
```

**Comment by richardanaya** [comment]
I know I haven't responded in like forever, but I did get not double locking.
